openapi: "3.0.0"
info:
  title: Ejemplo de API
  version: "1.0.0"
paths:
  /users:
    post:
      summary: Crear un usuario
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserInput"
      responses:
        '201':
          description: Usuario creado exitosamente
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserOutput"
components:
  schemas:
    UserInput:
      type: object
      properties:
        username:
          type: string
        email:
          type: string
          format: email
        readOnlyField:
          type: string
          x-readonly: true
      required:
        - username
        - email
    UserOutput:
      type: object
      properties:
        id:
          type: integer
        username:
          type: string
        email:
          type: string
          format: email
        readOnlyField:
          type: string
          x-readonly: true
