/**
 * Swagger Petstore
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import {Matches} from 'class-validator'
export class Pet { 
    
    id: number;
    @Matches(/^\d{3}-\d{2}-\d{4}$/)
    name: string;
    
    tag?: string;
}

