/**
 * User Management API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CreateUserDto } from './createUserDto';
import { CreateAdminDto } from './createAdminDto';


import { IsOptional, Validate, ValidateNested } from 'class-validator';
import { Type } from 'class-transformer';
import { IsOnlyOnePropertyPresent } from './IsOnlyOnePropertyPresent';          

/**
 * @class UserOrAdminDto
 * @export
 */
export class UserOrAdminDto {
        @IsOptional()
        @ValidateNested()
        @Type(() => CreateAdminDto)
        @Validate(IsOnlyOnePropertyPresent, ['CreateAdminDto'])
        CreateAdminDto: CreateAdminDto;
        @IsOptional()
        @ValidateNested()
        @Type(() => CreateUserDto)
        @Validate(IsOnlyOnePropertyPresent, ['CreateUserDto'])
        CreateUserDto: CreateUserDto;
}


