openapi: 3.0.0
info:
  title: User Management API
  version: 1.0.0
paths:
  /users:
    post:
      summary: Create a user or an admin
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserOrAdminDto'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: string
                example: "Usuario creado: John Doe"
        '400':
          description: Invalid input
components:
  schemas:
    CreateUserDto:
      type: object
      properties:
        name:
          type: string
          description: Name of the user
        email:
          type: string
          description: Email of the user
      required:
        - name
        - email

    CreateAdminDto:
      type: object
      properties:
        name:
          type: string
          description: Name of the admin
        role:
          type: string
          description: Role of the admin
      required:
        - name
        - role

    UserOrAdminDto:
      type: object
      oneOf:
        - $ref: '#/components/schemas/CreateUserDto'
        - $ref: '#/components/schemas/CreateAdminDto'
      discriminator:
        propertyName: type
        mapping:
          user: '#/components/schemas/CreateUserDto'
          admin: '#/components/schemas/CreateAdminDto'
      required:
        - type
      properties:
        type:
          type: string
          enum:
            - user
            - admin
